"""modified document model

Revision ID: ae7b58ec39eb
Revises: 87f68288479d
Create Date: 2025-11-29 18:11:54.654492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7b58ec39eb'
down_revision: Union[str, Sequence[str], None] = '87f68288479d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
