"""renmaed id to user_id in user model

Revision ID: 0516e3685f77
Revises: d31e2327f369
Create Date: 2025-12-14 16:55:46.020072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0516e3685f77'
down_revision: Union[str, Sequence[str], None] = 'd31e2327f369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id', new_column_name='user_id')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
