"""updated models

Revision ID: d31e2327f369
Revises: 1c1ddd22a173
Create Date: 2025-12-02 20:01:24.221032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd31e2327f369'
down_revision: Union[str, Sequence[str], None] = '1c1ddd22a173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # chat_history.created_at: auto-cast OK because it was TIMESTAMP already
    op.alter_column(
        'chat_history',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False
    )

    # documents.upload_timestamp: VARCHAR -> timestamptz, needs explicit USING
    op.alter_column(
        'documents',
        'upload_timestamp',
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="upload_timestamp::timestamptz"
    )

    # sessions.created_at: VARCHAR -> timestamptz, needs explicit USING
    op.alter_column(
        'sessions',
        'created_at',
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="created_at::timestamptz"
    )

    # user.created_at: if table already had rows, also must cast
    op.add_column(
        'user',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('documents', 'upload_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('chat_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
